---
title: ""
---

# Méthodologie

Les courbes présentées sur le site sont issues des scénarios de modélisations ayant impacté les politiques publiques mises en place en France. Elles ont principalement été produites par l'Institut Pasteur et l'Inserm. Les données n'étant à notre connaissance pas disponibles en accès libre, nous les avons extraites à partir des courbes des rapport en utilisant [WebPlotDigitilizer](https://automeris.io/WebPlotDigitizer/).

Pour permettre une évaluation appropriée des scénarios de modélisation, seuls les scénarios dont les hypothèses sont vérifiées ont été retenus, notamment les hyopthèses portant sur les mesures mises en place. Afin de ne pas introduire de biais (par exemple ne prendre que les scénarios qui surestimaient la réalité, ou l'inverse), nous avons étudié les scénarios de manière exhaustive. Nous avons analysé :

1.  toutes les modélisations issues des rapports de l'Institut Pasteur, publiés sur leur [page web](https://modelisation-covid19.pasteur.fr/)
2.  les modélisations cités dans les [rapports du Conseil Scientifique](https://solidarites-sante.gouv.fr/actualites/presse/dossiers-de-presse/article/conseil-scientifique-covid-19), ce qui nous à notamment mené à identifier des scénarios de Inserm pour janvier-février 2021
3.  les [modélisations de l'Imperial College pour le 1er confinement](https://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/report-12-global-impact-covid-19/), citée par le Conseil Scientifique et a eu un impact majeur sur les politiques publiques françaises
4.  une recherche google rétrospective avec dates délimitées pour chaque mois et les mots-clés "INSERM", "Pasteur", "modélisation", "scénario". Cela a permis d'identifier des scénarios non officiellement publiés mais néanmoins cités par la presse :[Institut Pasteur pour le 2ème confinement](https://www.lesechos.fr/economie-france/social/covid-la-decrue-dans-les-services-de-reanimation-esperee-en-france-dans-une-dizaine-de-jours-1261656)de novembre 2020, et Institut Pasteur pour le [déconfinement de l'Ile-de-France en mai 2020.](https://www.lesechos.fr/idees-debats/editos-analyses/pourquoi-philippe-a-douche-les-francais-1199309)

Enfin, nous nous concentrons sur les indicateurs hospitaliers, et excluons de notre analyse le nombre de cas. Cette exclusion est justifiée selon nous par deux raisons. La première est que le nombre de cas est un indicateur moins objectif que le nombre de lits occupés, car il dépend notamment de la propension des français à se faire tester, qui varie au cours du temps. Deuxièmement, le nombre de cas ne dit pas grand chose sur la dangerosité des infections. A partir de janvier 2022, le nombre de cas se situe à un niveau 10 fois supérieur aux chiffres pré-Omicron, sans que la pression hospitalière ne suive pour autant.

# Méthodologie détaillée

La liste exhaustive des scénarios de modélisation, et de leur inclusion ou non dans l'analyse du site (avec la raison) est disponible ci-dessous, ainsi que les liens renvoyant vers les rapports en question.

<details>

<summary>

**Modélisations de l'Institut Pasteur**

</summary>

-   [29 avril 2020](https://www.lesechos.fr/idees-debats/editos-analyses/pourquoi-philippe-a-douche-les-francais-1199309) : inclus (non officiellement publié mais retranscrit par la presse)
-   [25 septembre 2020](https://www.sdbio.eu/images/acymailing/Simulations%20Institut%20Pasteur%2025%2009%202020.pdf) : exclu (des mesures ont été prises en septembre, les scénarios ne sont donc plus comparable avec la réalité)
-   [30 octobre 2020](https://www.lesechos.fr/economie-france/social/covid-la-decrue-dans-les-services-de-reanimation-esperee-en-france-dans-une-dizaine-de-jours-1261656) : inclus (ce sont les modélisations du 2ème confinement, non publiées sur le site de l'Institut Pasteur mais retranscrites par la presse)
-   [8 février 2021](https://modelisation-covid19.pasteur.fr/variant/RapportInstitutPasteur_variants_8fevrier2021.pdf) : inclus
-   [23 février 2021](https://hal-pasteur.archives-ouvertes.fr/pasteur-03149525) : inclus
-   [29 mars 2021](https://www.eurosurveillance.org/content/10.2807/1560-7917.ES.2021.26.9.2100133) : pas de scénario dans le rapport
-   [6 avril 2021](https://www.thelancet.com/journals/eclinm/article/PIIS2589-5370(21)00281-9/fulltext) : exclu (les courbes présentées sont un contrefactuel de l'évolution épidémique en l'absence de vaccination)
-   [26 avril 2021](https://modelisation-covid19.pasteur.fr/loosening/Scenarios_de_levee_des_mesures_de_freinage_20210426.pdf) : inclus
-   [21 mai 2021](https://modelisation-covid19.pasteur.fr/loosening/Mise_a_jour_scenarios_de_levee_des_mesures_de_freinage_20210521.pdf) : inclus. Nous n'avons pas eu besoin d'analyser nous- mêmes, la comparaison étant déjà menée de manière informelle sur twitter par Simon Cauchemez en charge de l'équipe modélisation de l'Institut Pasteur
-   [9 juillet 2021](https://modelisation-covid19.pasteur.fr/variant/Institut_Pasteur_dynamique_du_variant_Delta_en_France_metropolitaine_20210709.pdf) : exclu (la mise en place du pass sanitaire n'était pas incluse dans les hypothèses de modélisation, les scénarios ne sont donc plus comparable avec la réalité)
-   [26 juillet 2021](https://modelisation-covid19.pasteur.fr/variant/Institut_Pasteur_Acceleration_vaccination_et_Delta_20210726.pdf) : inclus (les scénarios prennent en compte la mise en place du pass)
-   [5 août 2021](https://modelisation-covid19.pasteur.fr/variant/InstitutPasteur_Dynamiques_regionales_des_hospitalisations_20210805.pdf) : inclus (les scénarios prennent en compte la mise en place du pass sanitaire)
-   [6 septembre 2021](https://hal-pasteur.archives-ouvertes.fr/pasteur-03272638v2) : pas de scénarios dans le rapport
-   [4 octobre 2021](https://modelisation-covid19.pasteur.fr/scenarios/InstitutPasteur_scenariosCOVID19AutomneHiver_2021.pdf) : inclus
-   [29 novembre 2021](https://modelisation-covid19.pasteur.fr/scenarios/Institut_Pasteur_diminution_de_limmunit%C3%A9_et_rappel_20211129.pdf) : exclu (impact du variant Omicron 2 semaines plus tard, qui n'était pas pris en compte dans les modélisations). Nous avons tout de même pu comparer les projections à court terme durant la courte fenêtre de 2 semaines avant que le variant Omicron ne vienne fausser les résultats.
-   [2 décembre 2021](https://modelisation-covid19.pasteur.fr/scenarios/Institut_Pasteur_Complement_rapport_rappel_20211202.pdf) : exclu (impact du variant Omicron 2 semaines plus tard, qui n'était pas pris en compte dans les modélisations). Nous avons tout de même pu comparer les projections à court terme durant la courte fenêtre de 2 semaines avant que le variant Omicron vienne fausser les résultats.
-   [27 décembre 2021](https://modelisation-covid19.pasteur.fr/variant/Institut_Pasteur_Impact_dOmicron_sur_lepidemie_francaise_20211227.pdf) : inclus par le biais du rapport du 7 janvier. En effet il est précisé qu'"étant donné les incertitudes [...], il n'est pas possible de quantifier précisément l'impact qu'aura la vague Omicron". Une centaine de scénarios sont alors produits. Le rapport suivant du 7 janvier, que nous avons analysé, reprend pour base ce rapport après avoir exclu les scénarios ne collant pas aux propriétés d'Omicron.
-   [7 janvier 2022](https://modelisation-covid19.pasteur.fr/variant/InstitutPasteur_Complement_Analyse_Impact_Omicron_20220107_corrige.pdf) : inclus
-   [15 février 2022](https://modelisation-covid19.pasteur.fr/variant/Institut_Pasteur_Comparaison_Observations_projections_Omicron_20220215.pdf) : ce rapport ne produit pas de scénario mais une rétrospective portant sur le rapport précédent du 7 janvier. Nous en discutons dans notre analyse de ce dernier rapport.
-   [21 février 2022](https://modelisation-covid19.pasteur.fr/variant/Institut_Pasteur_Impact_BA_2_epidemie_francaise_20220221.pdf) : exclu. Ne se concentre que sur le nombre de cas, ce qui est un critère excluant de notre méthodologie comme expliqué plus haut.
-   [10 mars 2022](https://modelisation-covid19.pasteur.fr/variant/InstitutPasteur_impact_BA2_relachement_mesures_20220310.pdf) : exclu. Ne se concentre que sur le nombre de cas, ce qui est un critère excluant de notre méthodologie comme expliqué plus haut.

</details>

<details>

<summary>

**Modélisations de l'INSERM**

</summary>

-   modélisations de janvier-février 2021: inclues car apparaissant dans le [rapport du Conseil Scientifique du 29 janvier 2021](https://solidarites-sante.gouv.fr/IMG/pdf/note_eclairage_variants_modelisation_29_janvier_2021.pdf) suggérant l'instauration d'un confinement strict. Elles ont également été diffusées dans la presse. Ces modélisations sont apparues dans les rapports Inserm des [16 janvier 2021](https://www.epicx-lab.com/uploads/9/6/9/4/9694133/inserm_covid-19-voc_dominance-20210116.pdf), [2 février 2021](https://www.epicx-lab.com/uploads/9/6/9/4/9694133/inserm-covid-19-voc-lockdown-20210202.pdf) et [14 février 2021](https://www.epicx-lab.com/uploads/9/6/9/4/9694133/inserm_covid-19-voc_socialdistancing-20210214.pdf).

</details>

<details>

<summary>

**Modélisations de l'Imperial College**

</summary>

-   [modélisations du rapport 12](https://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/report-12-global-impact-covid-19/), et notamment son [appendice](https://www.imperial.ac.uk/media/imperial-college/medicine/mrc-gida/Imperial-College-COVID19-Global-unmitigated-mitigated-suppression-scenarios.xlsx): inclues car cités comme argument majeur en faveur du confinement dans le [rapport du Conseil Scientifique du 12 mars 2020.](https://solidarites-sante.gouv.fr/IMG/pdf/avis_conseil_scientifique_12_mars_2020.pdf)Il a aussi été cité par de nombreux médias comme ayant été un argument décivif pour trancher en faveur du confinement, par exemple dans [Le Monde](https://www.lemonde.fr/planete/article/2020/03/15/coronavirus-les-simulations-alarmantes-des-epidemiologistes-pour-la-france_6033149_3244.html) ou dans [Libération](https://www.liberation.fr/evenements-libe/2020/03/16/l-urgence-eviter-la-saturation-des-services-de-sante_1781988/).

</details>
